### ISSUE TITLE
Migrate from "System.Drawing" for cross-platform compatibility

### ISSUE THREAD

**Issue by WP-LKL** [diku-dk/DIKUArcade#45]
>The [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) NuGet package is now attributed as a Windows-specific library. The platform analyzer emits warning at compile time when compiling for non-Windows operating systems.
 -https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

### Replicating issue on Manjaro
1. Install gdi+
``$ pacman -S libgdiplus``
2. Build
``$ dotnet build``
3. Enable support in  runtimeconfig ../Galaga/bin/Debug/net6.0/Galaga.runtimeconfig.json:
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "configProperties": {
      "System.Drawing.EnableUnixSupport": true
    }
  }
}
```

``$ dotnet run``

```Unhandled exception. System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.
   at System.Drawing.Image..ctor()
   at System.Drawing.Bitmap..ctor(String filename)
   at DIKUArcade.Graphics.Texture..ctor(String filename) in /home/$user/Desktop/Github/DIKUGames/DIKUArcade/DIKUArcade/Graphics/Texture.cs:line 40
   at DIKUArcade.Graphics.Image..ctor(String imageFile) in /home/$user/Desktop/Github/DIKUGames/DIKUArcade/DIKUArcade/Graphics/Image.cs:line 10
   at Galaga.Game..ctor(WindowArgs windowArgs) in /home/$user/Desktop/Github/DIKUGames/Galaga/Game.cs:line 40
   at Galaga.Program.Main(String[] args) in /home/$user/Desktop/Github/DIKUGames/Galaga/Program.cs:line 11
```

>### [Recommended Action (docs)](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action)
>To use these APIs for cross-platform apps, migrate to one of the following libraries:
>* [ImageSharp](https://github.com/SixLabors/ImageSharp)
>* [SkiaSharp](https://github.com/mono/SkiaSharp)
>* [Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics)

**Comment by WilliamDue** [comment]
We have migrated now.
